---
- hosts: solr
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update yum
      yum:
        update_cache: yes

  handlers:
    - name: restart solr
      systemd:
        name: solr
        state: restarted
        enabled: yes
  tasks:
    - name: install java.
      yum:
        name: java-11-openjdk
        state: present

    - name: Download solr
      get_url:
        url: "https://downloads.apache.org/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_chcksum }}"

    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: yes
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.md"

    - name: Run solr install
      shell: >
       {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
       {{ download_dir }}/solr-{{ solr_version }}.tgz
       -i /opt
       -d /var/solr
       -u solr
       -s solr
       -p 8983
       creates={{ solr_dir }}/bin/solr 
  
    - name: enabled solr
      systemd:
        name: solr
        state: restarted
        enabled: yes
